name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linter
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.0
          elixir-version: 1.17
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix credo --strict --ignore design.alias
      - run: mix format --check-formatted

  test:
    strategy:
      matrix:
        http_server: [Httpd, Plug.Cowboy, Bandit]
        version:
          - elixir: 1.18
            otp: 27.0
          - elixir: 1.16
            otp: 26.0
          - elixir: 1.13
            otp: 25.0
    runs-on: ubuntu-latest
    name: OTP ${{matrix.version.otp}} / Elixir ${{matrix.version.elixir}} / ${{matrix.http_server}}
    env:
      MIX_ENV: test
      HTTP_SERVER: ${{matrix.http_server}}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.version.otp}}
          elixir-version: ${{matrix.version.elixir}}
      - run: mix deps.get mix compile --warnings-as-errors
      - run: mix test
